version: '3.8'

services: 
  api:
    image: gabrielamds/devops-api:latest
    container_name: devops-api
    ports:
      - "5000:5000"
    restart: always
    networks:
      - devops-network
  
  nginx:
    image: nginx:latest
    container_name: devops-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    
    depends_on:
      - api
    networks:
      - devops-network
    restart: always

networks:
  devops-network:
    driver: bridge
