name: CI Fase 2 - Python + Docker + EC2

on: 
  push:
    branches: ["main"]
  pull_request:
      branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependências Python
        run: |
          python -m pip install --upgrade pip
          pip install flask pytest

      - name: Rodar testes
        run:  |
          pytest

  docker-deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3
        
      - name: Login no Docker
        uses: docker/login-action@v2
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

      
      - name: Build imagem Docker
        run: docker build -t gabrielamds/devops-api:latest .

      - name: Push da imagem pro DockerHub
        run: docker push gabrielamds/devops-api:latest

      - name: Deploy no servidor EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          script: |
              docker pull gabrielamds/devops-api:latest
              docker pull nginx:latest
              docker-compose down || true
              docker-compose up -d
